# Generated by Django 3.0.2 on 2020-03-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0003_auto_20200301_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_cover_photo', models.ImageField(upload_to='event_cover/')),
                ('eventname', models.CharField(max_length=255, unique=True)),
                ('eventlocation', models.TextField()),
                ('description', models.TextField()),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Clubs')),
            ],
        ),
    ]
