# Generated by Django 3.0.2 on 2020-05-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_cover_photo', models.ImageField(upload_to='event_cover/')),
                ('eventname', models.CharField(max_length=255, unique=True)),
                ('eventlocation', models.TextField()),
                ('description', models.TextField()),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Clubs')),
            ],
        ),
        migrations.CreateModel(
            name='Perticipants_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('std_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Clubs')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Events')),
            ],
        ),
    ]
