# Generated by Django 3.0.2 on 2020-05-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='image',
            field=models.ImageField(default='accounts/blankimage.jpg', upload_to='accounts/'),
            preserve_default=False,
        ),
    ]
