# Generated by Django 3.0.2 on 2020-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_label', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='academic_calendar/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
