# Generated by Django 3.0.2 on 2020-02-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubname', models.CharField(max_length=255, unique=True)),
                ('shortname', models.CharField(max_length=10)),
                ('clubemail', models.EmailField(blank=True, max_length=255, verbose_name='email address')),
                ('logo', models.ImageField(upload_to='club_logo/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
