# Generated by Django 3.0.2 on 2020-05-06 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('std_id', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('semister', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)])),
                ('completed_credit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('approved', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Clubs')),
            ],
        ),
    ]
