# Generated by Django 3.0.2 on 2020-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
